name: Build Tkinter EXE with Icon

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller pynput keyboard

      - name: Show files before build
        run: dir

      - name: Build EXE with Icon
        run: |
          pyinstaller --onefile --noconsole --icon=hamster_icon.ico AutoClicker.py

      - name: Show dist contents
        run: dir dist

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoClicker_Executable
          path: dist/AutoClicker.exe
