name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller pynput keyboard

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole AutoClicker_GUI.py

      - name: List build output (for debug)
        run: dir dist

      - name: Upload built EXE
        uses: actions/upload-artifact@v3
        with:
          name: AutoClicker_EXE
          path: dist/AutoClicker_GUI.exe
