name: Build PyQt5 EXE with Icon

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller PyQt5 pynput keyboard

      - name: Build EXE with Icon
        run: |
          pyinstaller --onefile --noconsole --icon=hamster_icon.ico AutoClicker_PyQt_Standalone.py

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoClicker_PyQt_Executable
          path: dist/AutoClicker_PyQt_Standalone.exe
